
export const LOAD_FLIGHT = 'LOAD_FLIGHT';
export const LOAD_FLIGHT_SUCCESS = 'LOAD_FLIGHT_SUCCESS';
export const EDIT_FLIGHT_ANCILLARY = 'EDIT_FLIGHT_ANCILLARY';
export const EDIT_FLIGHT_ANCILLARY_SUCCESS = 'EDIT_FLIGHT_SEAT_SUCCESS';