export const LOAD_PASSENGERS='LOAD_PASSENGERS';
export const LOAD_PASSENGERS_SUCCESS='LOAD_PASSENGERS_SUCCESS';
export const EDIT_PASSENGER_SEAT='EDIT_PASSENGER_SEAT';
export const EDIT_PASSENGER_SEAT_SUCCESS='EDIT_PASSENGER_SEAT_SUCCESS';

export const ADD_PASSENGER='ADD_PASSENGER';
export const ADD_PASSENGER_SUCCESS='ADD_PASSENGER_SUCCESS';

export const DELETE_PASSENGER='DELETE_PASSENGER';
export const DELETE_PASSENGER_SUCCESS='DELETE_PASSENGER_SUCCESS';